ALTER SESSION SET CONTAINER = XEPDB1;

   CREATE USER beatify IDENTIFIED BY beatify123
       DEFAULT TABLESPACE users
       QUOTA UNLIMITED ON users;

   GRANT CONNECT, RESOURCE TO beatify;
   GRANT CREATE SESSION   TO beatify;
   GRANT CREATE TABLE     TO beatify;
   GRANT CREATE SEQUENCE  TO beatify;
   GRANT CREATE VIEW      TO beatify;
   GRANT CREATE PROCEDURE TO beatify;
   GRANT CREATE TRIGGER   TO beatify;