-- Tabla de preferencias de género por cliente
-- Ejecutar una sola vez sobre el esquema BEATIFY

CREATE TABLE CLIENTE_GENERO (
    CLIENTE_id_cliente  INTEGER  NOT NULL,
    GENERO_id_genero    INTEGER  NOT NULL
);

ALTER TABLE CLIENTE_GENERO
    ADD CONSTRAINT CLIENTE_GENERO_PK
    PRIMARY KEY (CLIENTE_id_cliente, GENERO_id_genero);

ALTER TABLE CLIENTE_GENERO
    ADD CONSTRAINT CLIENTE_GENERO_CLIENTE_FK
    FOREIGN KEY (CLIENTE_id_cliente)
    REFERENCES CLIENTE (id_cliente)
    ON DELETE CASCADE;

ALTER TABLE CLIENTE_GENERO
    ADD CONSTRAINT CLIENTE_GENERO_GENERO_FK
    FOREIGN KEY (GENERO_id_genero)
    REFERENCES GENERO (id_genero)
    ON DELETE CASCADE;
